### ISSUE TITLE
Drive-by notes on Version 

### ISSUE THREAD

**Issue by Eh2406** [konstin/pep440-rs#12]
I have never used this crate. I was just reviewing it for my own edification. As such feel free to ignore and close this issue. I was looking at the definition of [`Version`](https://github.com/konstin/pep440-rs/blob/main/src/version.rs#L268C12-L268C20) and noticed two things I wanted to understand better.

I see a lot of use of `usize` where I was expecting `u{number}`, does validity of pep440 really depend on the pointer size of the target? That seems really unexpected that a version would be valid on 64 bites os but that same version would not be valid on a 32 bites os. Although thinking about it if the canonical implementation is in Python that maybe they should all be arbitrary width integers. 🤯 

There also seemed to be a number of places where we can have an arbitrary number of strings. If these strings are all taken from the original input then they could be `&str` or `Cow<str>`, but lifetimes are probably not worth the performance. I wonder whether a small string optimized crate would work well here. The one from [semver](https://github.com/dtolnay/semver/blob/master/src/identifier.rs) is probably the most optimized for this use case, but it's not a public API. There are many other options, most of which would be very easy to drop in.

**Comment by konstin** [comment]
> I see a lot of use of usize where I was expecting u{number}, does validity of pep440 really depend on the pointer size of the target? That seems really unexpected that a version would be valid on 64 bites os but that same version would not be valid on a 32 bites os. Although thinking about it if the canonical implementation is in Python that maybe they should all be arbitrary width integers. 🤯

Totally! We switched to `u64` now, i didn't previously consider people used versions such as `20230628214621`.

> There also seemed to be a number of places where we can have an arbitrary number of strings. If these strings are all taken from the original input then they could be &str or Cow<str>, but lifetimes are probably not worth the performance. 

We only store strings in `LocalSegment`, which is generally rare ("Local version identifiers SHOULD NOT be used when publishing upstream projects to a public index server, but MAY be used to identify private builds created directly from the project source")
