### ISSUE TITLE
Implement `Version` comparison magic methods

### ISSUE THREAD

**Issue by KOLANICH** [konstin/pep440-rs#2]

**Comment by konstin** [comment]
Please explain what exactly you expect to be implemented, i.e. what kind of code and if it's on the rust side or on the python side, on what the semantics are supposed to be

**Comment by KOLANICH** [comment]
It can be implemented on either side. I guess the easiest way is to just reuse the impl from `packaging.version.Version` and create a Python wrapper.

To be honest I'm not sure if this package is needed at all. I have benchmarked it (using `timeit`, release build), it is `~5` times faster than `packaging.version.Version` in cpython 3.9 and `~2` times faster when `packaging.version.Version` is run in pypy 3.7 and this package is run in cpython 3.9.

```python
from timeit import timeit

from packaging.version import Version

try:
	from pep440_rs import Version as RVersion
except ImportError:
	RVersion = None

ITERS = 100000
t1 = timeit(number=ITERS, stmt=lambda: Version("1!1.2.rev33+123456"))

if RVersion:
	ratio = 10
	t2 = timeit(number=ITERS * ratio, stmt=lambda: RVersion("1!1.2.rev33+123456")) / ratio
	print(t2)  # 0.34940626439638434
else:
	t2 = 0.34964482330251484

print(t1 / t2)  # 5.056851570606841 cpython, 1.9029041982681703 pypy
```

**Comment by konstin** [comment]
I've removed the pyo3 bindings, they should go into a separate crate if needed.
