### ISSUE TITLE
Plans to publish pep440-rs

### ISSUE THREAD

**Issue by cnpryer** [konstin/pep440-rs#4]
Hi! Love this. Thanks for building it!

I see the issue you have tagged in the readme as the blocker. Is there any update on that? Also is there anything I can do to help get this project published?

**Comment by konstin** [comment]
just waiting on https://github.com/PyO3/pyo3/pull/2786 to get merged an published, which i forgot to update

**Comment by konstin** [comment]
it's now published published on crates.io and pypi
